<a href="https://colab.research.google.com/github/crazygovind/AI-Foundation-Whitehat-Jr/blob/master/12_Project_NumPy_Arrays_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

 1. Python Lists I

 2. NumPy Arrays I

---

#### Activity 1: Create a 3 X 3 Matrix

To create a 3x3 matrix with values ranging from 2 to 10.

**For Example**:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import `numpy` module.

  - **Step 2**: Use `arange()` function to create array of numbers from 2 to 10 and `reshape()` function to reshape your array into another array having 3 rows and 3 columns. Store this reshaped array in a variable `x`.

  - **Step 3**: Print variable `x` to get the output.

 

In [ ]:
# Write your code here
# Step 1: Import numpy module 
import numpy as np
# Step 2: Declare a variable 'x' to store the result and use 'arange()' and 'reshape()' functions
x= np.arange(2,11).reshape(3,3)
# Step 3: Print the variable 'x' to see the output
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


---

#### Activity 2: Change Dimension of an Array and Convert the NumPy Array into a List

Write a program to change the dimension of an array (say `my_arr =[1, 2, 3, 4, 5, 6, 7, 8, 9]`) into a 3 X 3 (3 rows and 3 columns) array and convert this NumPy array into a list.

**For Example:**
```
Original array is [1 2 3 4 5 6 7 8 9]
Dimension is (9,)
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

The data type of the converted variable is 
 list
```


In [ ]:
# Write your code here
# Import numpy module 
import numpy as np
# Create a NumPy array containing a list of numbers
num_array=np.arange(1,10)
# Print the dimension of the array 
print(num_array.ndim)
# Change the dimension of the array into a 3 X 3
num_array=num_array.reshape(3,3)
# Print the array 
print(num_array)
# Convert the NumPy array into a Python list 
num_array=list(num_array)
# Use type() function to verify the conversion
type(num_array)

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]


list

---

#### Activity 3: Find Square Root and Calculate the value of $c$ 

Write a program to perform following two tasks:
-  Print the square root of numbers in the list.
- Compute the value of $c$ in the equation $c=\sqrt(a^2 + b^2)$. 

**For Example**:

```
list1 = [4, 16, 9, 1, 25]
[2   4    3   1    5 ]
If a=27
   b=39
The value of c =  47.43416490252569
```
**Hint:** Use `np.sqrt()` function.
 

In [ ]:
list1 = [4, 16, 9, 1, 25]

for i in list1:
  x=np.sqrt(i)
  print(x)
  
a=27
b=39

c=np.sqrt((a**2)+(b**2))
print('The value of c =  ',c)


2.0
4.0
3.0
1.0
5.0
The value of c =   47.43416490252569


---