<a href="https://colab.research.google.com/github/crazygovind/AI-Foundation-Whitehat-Jr/blob/master/13_Project_Claude_Shannon_Algorithm_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

  1.  Claude Shannon Algorithm I

---

### Activities

#### Activity 1: 3D NumPy array

Write a program to create a three-dimensional NumPy array which has 4 blocks, 4 rows and 4 columns such that all the initial items are `0`.

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import `numpy` module.

  - **Step 2**: Pass `(4, 4, 4 )` inside the `shape` attribute of the `zeros()` function to create a 3D NumPy array of size (4, 4, 4) whose all the elements are 0. Store the array in a variable `three_d_arr`.

In [2]:
# Create a 3D NumPy array of size (4, 4, 4) whose all the elements are 0.
# Step 1: Import numpy module.
import numpy as np
# Step 2: Pass '(4, 4, 4 )' inside the 'shape' attribute of the 'zeros()' function
three_d_arr=np.zeros(shape=(4,4,4),dtype=int)
three_d_arr

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

---

#### Activity 2: Accessing elements in a 3D array.

Given a 3D NumPy array of size (2, 2, 2) whose all the elements are 0,

```
three_d_arr = [[[0 0],
               [0 0]],

              [[0 0],
              [0 0]]]
```

write a program to generate a random number between 10 and 50 at (0, 1, 1) position of the `three_d_arr`. If the random number generated is greater than 20 then, update the 1st element (`update_needed` in the below array) as `50`, else, update it as `20`.

```
three_d_arr = [[[0 update_required],
               [0 random_number]],

              [[0 0],
              [0 0]]]
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import the `random` module.

  - **Step 2**: Update the `(0, 1, 1)` position of the `three_d_arr` with a random number between `10` and `50` (including both).

  - **Step 3**: Check whether the random number generated is greater than `20` using an `if` condition. 

     - If the condition is `True`, update the `0` at `(0, 0, 1)` i.e. `update_required` position with `50`.

     - Else, update it as `20`.

In [3]:
# 3D NumPy array of size (2, 2, 2) whose all the elements are 0.
import numpy as np

three_d_arr = np.zeros(shape=(2, 2, 2), dtype=int)
three_d_arr

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [7]:
# Write your code here to generate a random number between 10 and 50 at (0,1,1)
import random
random_number=random.randint(10,50)
print(random_number)

30


In [8]:
# Check whether the random number generated is greater than 20
if random_number > 20:
  three_d_arr[0,0,1]=50
  # If the condition is 'True', update the '0' at '(0, 0, 1)' position with '50'.

# print the resultant 'three_d_array' array
three_d_arr

array([[[ 0, 50],
        [ 0,  0]],

       [[ 0,  0],
        [ 0,  0]]])

---