<a href="https://colab.research.google.com/github/crazygovind/AI-Foundation-Whitehat-Jr/blob/master/15_Project_NumPy_Arrays_II.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

1. Python Lists 

2. List Comprehension

3. NumPy Arrays



---

#### Activity 1: Create and update a null NumPy array 

Create a null NumPy array of size 10 and update the sixth value to 11.

A null array is basically an array with all elements as `0`.

Follow the steps given below to achieve the desired result:

- **Step 1:** Import the Numpy module as `np`.

- **Step 2**: Create a null array by passing the size i.e. `10` inside the `np.zeros()` function and store it in a variable `null_arr`. 

- **Step 3**: Print the null array.

- **Step 4**: Now update the sixth element of the array by using **list indexing** method. As you need to update the sixth element, the index must be `5`.

- **Step 5**: Print the updated array in the output.



In [ ]:
# Write a program to create Null array of size 10 and update the sixth value to 11.
import numpy as np 
null_array=np.zeros(10)
print(null_array)
null_array[5]=6
print(null_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 6. 0. 0. 0. 0.]


---

#### Activity 2: Populate a number list

Write a program that populates a list by numbers that lie in the range of 0 to 49 and are also divisible by 5. Use the **List Comprehension** method.

**Output**: `[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]`




In [ ]:
# Write a program to populate a number list divisible by 5 in a range of 0 - 49
number_list=np.arange(0,50,5)
print(number_list)

[ 0  5 10 15 20 25 30 35 40 45]


---

#### Activity 3: Convert a list into an array 

Write a program to convert a list of numeric values into a one-dimensional NumPy array.

**For Example:**

**Input**: `lst = [12.23, 13.32, 100, 36.32]`

Data type of `lst` = `list`

**Output**: `numpy_array = [12.23, 13.32, 100, 36.32]`

Data type of `numpy_array` = `numpy.ndarray`

In [ ]:
# Write a program to convert a list into one dimensional NumPy array
first=[12.23, 13.32, 100, 36.32]
numpy_array=np.array(first)
print(numpy_array)

[ 12.23  13.32 100.    36.32]


---